matrix:
  include:
    - language: java
      jdk: oraclejdk8
      before_script:
        - cd srv
      script:
        - ./mvnw clean install -B

    - language: node_js
      before_script:
        - cd clt
      script:
        - npm install