matrix:
  include:
    - language: java
      jdk: oraclejdk8
      before_script:
        - cd srv
      script:
        - mvn clean install

    - language: node_js
      node_js:
        - "8"
      before_script:
        - cd clt
        - npm install -g @angular/cli
      script:
        - ng build