matrix:
  include:
    - language: java
      jdk: oraclejdk8
      before_script:
        - cd srv
      script:
        - mvn clean install
 #     deploy:
 #       provider: gae
 #       keyfile: "minyan-karov-a6aafc2e654d.json"
 #       project: "minyan-karov-210003"
  
  
    - language: node_js
      node_js:
        - "8"
      before_script:
        - cd clt
        - npm install -g @angular/cli
        - npm install
      script:
        - ng build